[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.2.6"
matplotlib = "^3.10.3"
scipy = "^1.15.3"
scikit-learn = "^1.6.1"
openai = "^1.91.0"
datasets = "^3.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
